version: '3'
services:
  App:
    container_name: RivalAppContainer
    image: ikasetebo/laravel:v7.2.01
    networks:
      - rival_app_bridge
      - rival_dev_cache
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - D:/Repos/RIVAL-Learning/app/:/usr/share/nginx/html/
      - D:/Repos/RIVAL-Learning/nginx-conf/sites-enabled/default:/etc/nginx/sites-enabled/default
      - D:/Repos/RIVAL-Learning/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - D:/Repos/RIVAL-Learning/nginx-conf/mime.types:/etc/nginx/mime.types
      - D:/Repos/RIVAL-Learning/php-conf/fpm/php.ini:/etc/php/7.2/fpm/php.ini
      - D:/Repos/RIVAL-Learning/shared/:/shared/
    depends_on:
      - db
  db:
    container_name: RivalDBContainer
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - D:/Repos/RIVAL-Learning/database/mysql:/var/lib/mysql
    networks:
      - rival_app_bridge
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
  adminer:
    container_name: AdminerContainer
    image: adminer:latest
    ports:
      - '8000:8080'
    networks:
      - rival_app_bridge
    depends_on:
      - db
  redis:
    container_name: RivalCacheContainer
    image: redis:4.0
    networks:
      - rival_dev_cache
    depends_on:
      - App
  
  
networks:
  rival_app_bridge:
    driver: bridge
  rival_dev_cache:
    driver: bridge


